"""Offline capture IO entry points for mmwcore."""

from __future__ import annotations

from ._mmwcli_contract import MmwcliRawCaptureContract
from .adc_file import ADCFileFrameReader, load_adc_cube, load_adc_file
from .capture_stream import (
    MMWCLI_CAPTURE_STREAM_SCHEMA_V1,
    MMWCLI_CAPTURE_STREAM_TERMINAL_SCHEMA_V1,
    CaptureStream,
    CaptureStreamAbort,
    CaptureStreamAborted,
    CaptureStreamCommit,
    CaptureStreamContract,
    CaptureStreamError,
    CaptureStreamReader,
    CaptureStreamStateError,
    ProvisionalADCFrame,
    ProvisionalRangeDopplerFrame,
    open_capture_stream,
)
from .mmwcli_capture import (
    MMWCLI_CAPTURE_SESSION_SCHEMA_V1,
    ADCFileCapture,
    RangeDopplerPreset,
    open_capture,
)
from .multisensor_capture import (
    MMWCLI_MULTISENSOR_SESSION_SCHEMA_V1,
    MMWCLI_SENSOR_INDEX_SCHEMA_V1,
    MappedTimeInterval,
    MultisensorCapture,
    MultisensorItem,
    MultisensorSource,
    MultisensorSyncEvent,
    TrainingKey,
    causal_match,
    open_multisensor_capture,
)
from .packets import (
    DCA1000_PACKET_HEADER_BYTES,
    DCA1000_PACKET_PAYLOAD_BYTES,
    DCA1000_PACKET_PAYLOAD_INT16_VALUES,
    DCA1000Packet,
    PacketLossStats,
    assemble_dca1000_frame,
    assemble_dca1000_frame_bytes,
    parse_dca1000_packet,
    read_dca1000_frame_from_packets,
    reorder_dca1000_packets,
)

__all__ = [
    "DCA1000_PACKET_HEADER_BYTES",
    "ADCFileFrameReader",
    "ADCFileCapture",
    "DCA1000_PACKET_PAYLOAD_BYTES",
    "DCA1000_PACKET_PAYLOAD_INT16_VALUES",
    "DCA1000Packet",
    "PacketLossStats",
    "MMWCLI_CAPTURE_SESSION_SCHEMA_V1",
    "MMWCLI_CAPTURE_STREAM_SCHEMA_V1",
    "MMWCLI_CAPTURE_STREAM_TERMINAL_SCHEMA_V1",
    "MMWCLI_MULTISENSOR_SESSION_SCHEMA_V1",
    "MMWCLI_SENSOR_INDEX_SCHEMA_V1",
    "MappedTimeInterval",
    "MmwcliRawCaptureContract",
    "MultisensorCapture",
    "MultisensorItem",
    "MultisensorSource",
    "MultisensorSyncEvent",
    "CaptureStreamAbort",
    "CaptureStreamAborted",
    "CaptureStream",
    "CaptureStreamCommit",
    "CaptureStreamContract",
    "CaptureStreamError",
    "CaptureStreamReader",
    "CaptureStreamStateError",
    "ProvisionalADCFrame",
    "ProvisionalRangeDopplerFrame",
    "RangeDopplerPreset",
    "TrainingKey",
    "assemble_dca1000_frame",
    "assemble_dca1000_frame_bytes",
    "causal_match",
    "load_adc_cube",
    "load_adc_file",
    "open_capture",
    "open_capture_stream",
    "open_multisensor_capture",
    "parse_dca1000_packet",
    "read_dca1000_frame_from_packets",
    "reorder_dca1000_packets",
]
