"""Offline capture IO entry points for mmwcore."""

from __future__ import annotations

from ._mmwcli_contract import MmwcliRawCaptureContract
from .adc_archive import (
    ADCArchive,
    ADCArchiveError,
    open_adc_archive,
    write_adc_archive,
)
from .adc_archive_reader import ADCArchiveFrameReader
from .adc_file import ADCFileFrameReader, load_adc_cube, load_adc_file
from .adc_reader import ADCFrameReader
from .capture_stream import (
    MMWCLI_CAPTURE_STREAM_SCHEMA_V1,
    MMWCLI_CAPTURE_STREAM_TERMINAL_SCHEMA_V1,
    CaptureStream,
    CaptureStreamAbort,
    CaptureStreamAborted,
    CaptureStreamCommit,
    CaptureStreamContract,
    CaptureStreamError,
    CaptureStreamReader,
    CaptureStreamStateError,
    ProvisionalADCFrame,
    ProvisionalRangeDopplerFrame,
    open_capture_stream,
)
from .mmwcli_capture import (
    MMWCLI_CAPTURE_SESSION_SCHEMA_V1,
    ADCFileCapture,
    MmwcliCaptureMetadata,
    RangeDopplerPreset,
    open_capture,
    open_mmwcli_capture_metadata,
)
from .multisensor_capture import (
    MMWCLI_MULTISENSOR_SESSION_SCHEMA_V1,
    MMWCLI_SENSOR_INDEX_SCHEMA_V1,
    MappedTimeInterval,
    MultisensorArtifactMetadata,
    MultisensorCapture,
    MultisensorCaptureMetadata,
    MultisensorItem,
    MultisensorSource,
    MultisensorSourceMetadata,
    MultisensorSourceTimeline,
    MultisensorSyncEvent,
    MultisensorTimelineItem,
    TrainingKey,
    causal_match,
    open_multisensor_capture,
    open_multisensor_capture_metadata,
    open_multisensor_source_timeline,
)
from .multisensor_stream import (
    MMWCLI_MULTISENSOR_STREAM_SCHEMA_V1,
    MMWCLI_MULTISENSOR_STREAM_TERMINAL_SCHEMA_V1,
    MultisensorRadarConfig,
    MultisensorSourceEnd,
    MultisensorStream,
    MultisensorStreamAbort,
    MultisensorStreamAborted,
    MultisensorStreamCommit,
    MultisensorStreamContract,
    MultisensorStreamError,
    MultisensorStreamReader,
    MultisensorStreamSource,
    MultisensorStreamStateError,
    ProvisionalMultisensorItem,
    ProvisionalMultisensorRangeDoppler,
    open_multisensor_stream,
)
from .packets import (
    DCA1000_PACKET_HEADER_BYTES,
    DCA1000_PACKET_PAYLOAD_BYTES,
    DCA1000_PACKET_PAYLOAD_INT16_VALUES,
    DCA1000Packet,
    PacketLossStats,
    assemble_dca1000_frame,
    assemble_dca1000_frame_bytes,
    parse_dca1000_packet,
    read_dca1000_frame_from_packets,
    reorder_dca1000_packets,
)

__all__ = [
    "DCA1000_PACKET_HEADER_BYTES",
    "ADCFileFrameReader",
    "ADCFrameReader",
    "ADCArchiveFrameReader",
    "ADCFileCapture",
    "ADCArchive",
    "ADCArchiveError",
    "DCA1000_PACKET_PAYLOAD_BYTES",
    "DCA1000_PACKET_PAYLOAD_INT16_VALUES",
    "DCA1000Packet",
    "PacketLossStats",
    "MMWCLI_CAPTURE_SESSION_SCHEMA_V1",
    "MmwcliCaptureMetadata",
    "MMWCLI_CAPTURE_STREAM_SCHEMA_V1",
    "MMWCLI_CAPTURE_STREAM_TERMINAL_SCHEMA_V1",
    "MMWCLI_MULTISENSOR_SESSION_SCHEMA_V1",
    "MMWCLI_MULTISENSOR_STREAM_SCHEMA_V1",
    "MMWCLI_MULTISENSOR_STREAM_TERMINAL_SCHEMA_V1",
    "MMWCLI_SENSOR_INDEX_SCHEMA_V1",
    "MappedTimeInterval",
    "MultisensorArtifactMetadata",
    "MmwcliRawCaptureContract",
    "MultisensorCapture",
    "MultisensorCaptureMetadata",
    "MultisensorItem",
    "MultisensorRadarConfig",
    "MultisensorSource",
    "MultisensorSourceMetadata",
    "MultisensorSourceTimeline",
    "MultisensorSourceEnd",
    "MultisensorStream",
    "MultisensorStreamAbort",
    "MultisensorStreamAborted",
    "MultisensorStreamCommit",
    "MultisensorStreamContract",
    "MultisensorStreamError",
    "MultisensorStreamReader",
    "MultisensorStreamSource",
    "MultisensorStreamStateError",
    "MultisensorSyncEvent",
    "MultisensorTimelineItem",
    "CaptureStreamAbort",
    "CaptureStreamAborted",
    "CaptureStream",
    "CaptureStreamCommit",
    "CaptureStreamContract",
    "CaptureStreamError",
    "CaptureStreamReader",
    "CaptureStreamStateError",
    "ProvisionalADCFrame",
    "ProvisionalMultisensorItem",
    "ProvisionalMultisensorRangeDoppler",
    "ProvisionalRangeDopplerFrame",
    "RangeDopplerPreset",
    "TrainingKey",
    "assemble_dca1000_frame",
    "assemble_dca1000_frame_bytes",
    "causal_match",
    "load_adc_cube",
    "load_adc_file",
    "open_capture",
    "open_mmwcli_capture_metadata",
    "open_capture_stream",
    "open_adc_archive",
    "open_multisensor_capture",
    "open_multisensor_capture_metadata",
    "open_multisensor_source_timeline",
    "open_multisensor_stream",
    "parse_dca1000_packet",
    "read_dca1000_frame_from_packets",
    "reorder_dca1000_packets",
    "write_adc_archive",
]
