"""Typed, physically explicit mmWave radar processing."""

from __future__ import annotations

from importlib.metadata import version

from .io import (
    ADCArchive,
    CaptureStream,
    MappedTimeInterval,
    MmwcliCaptureMetadata,
    MultisensorArtifactMetadata,
    MultisensorCapture,
    MultisensorCaptureMetadata,
    MultisensorItem,
    MultisensorSource,
    MultisensorSourceMetadata,
    MultisensorSourceTimeline,
    MultisensorStream,
    MultisensorStreamCommit,
    MultisensorSyncEvent,
    MultisensorTimelineItem,
    ProvisionalMultisensorItem,
    ProvisionalRangeDopplerFrame,
    TrainingKey,
    causal_match,
    open_adc_archive,
    open_capture,
    open_capture_stream,
    open_mmwcli_capture_metadata,
    open_multisensor_capture,
    open_multisensor_capture_metadata,
    open_multisensor_source_timeline,
    open_multisensor_stream,
    write_adc_archive,
)

__all__ = [
    "__version__",
    "ADCArchive",
    "CaptureStream",
    "MappedTimeInterval",
    "MmwcliCaptureMetadata",
    "MultisensorArtifactMetadata",
    "MultisensorCapture",
    "MultisensorCaptureMetadata",
    "MultisensorItem",
    "MultisensorSource",
    "MultisensorSourceMetadata",
    "MultisensorSourceTimeline",
    "MultisensorStream",
    "MultisensorStreamCommit",
    "MultisensorSyncEvent",
    "MultisensorTimelineItem",
    "ProvisionalMultisensorItem",
    "ProvisionalRangeDopplerFrame",
    "TrainingKey",
    "causal_match",
    "open_adc_archive",
    "open_capture",
    "open_mmwcli_capture_metadata",
    "open_capture_stream",
    "open_multisensor_capture",
    "open_multisensor_capture_metadata",
    "open_multisensor_source_timeline",
    "open_multisensor_stream",
    "write_adc_archive",
]

__version__ = version("mmwcore")
